### ISSUE TITLE
Mala indentación

### ISSUE THREAD

**Issue by FcoJavierGlez** [iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez#1]
Échale un ojo a esta línea, creo que la tienes mal indentada:

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez/blob/ed8438ff66f59f7de1838462df837f27a43ff3e8/Ejercicio1.java#L17

**Comment by jlalvarezfernandez** [comment]
gracias por la corrección, lo arreglare con la mayor brevedad

**Comment by jaimerabasco** [comment]
Solo cierras 1 issue, en lugar de los 4 que pide la práctica @jlalvarezfernandez  @FcoJavierGlez

**Comment by jlalvarezfernandez** [comment]
he realizado la identacion
