### ISSUE TITLE
Errata comentario

### ISSUE THREAD

**Issue by FcoJavierGlez** [iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez#1]
Tienes una errata en esta línea

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez/blob/555e43b8c27e35f556f5f7abb9d5b3afa17718fd/Ejercicio20.java#L14

**Comment by jlalvarezfernandez** [comment]
gracias, voy a mirarlo

**Comment by jlalvarezfernandez** [comment]
corregida linea 14
