### ISSUE TITLE
Errata línea 17

### ISSUE THREAD

**Issue by FcoJavierGlez** [iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez#2]
Tienes una errata en la línea 17

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez/blob/6521b6c39ed3063f4786297c93e088dab4ef548e/Ejercicio20.java#L17

**Comment by jlalvarezfernandez** [comment]
gracias, lo volveré a corregir

**Comment by FcoJavierGlez** [comment]
Si necesitas que te eche una mano me ofrezco a ello.
