### ISSUE TITLE
Errata línea 19

### ISSUE THREAD

**Issue by FcoJavierGlez** [iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez#3]
Tienes varias erratas en la línea 19

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez/blob/29a37048c66ad502449711b53534ce0020059e19/Ejercicio20.java#L19

**Comment by jlalvarezfernandez** [comment]
tengo que mejorar mi escritura por teclado

**Comment by FcoJavierGlez** [comment]
Me tienes que recuerdar que te recomiende un curso de mecanografía
