### ISSUE TITLE
Errata en la línea 20

### ISSUE THREAD

**Issue by FcoJavierGlez** [iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez#4]
Tienes una errata en la línea 20

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-jlalvarezfernandez/blob/29a37048c66ad502449711b53534ce0020059e19/Ejercicio20.java#L20

**Comment by jlalvarezfernandez** [comment]
ya no voy a corregir mas, déjeme en paz caballero

**Comment by FcoJavierGlez** [comment]
La perseverancia es una virtud José Luis
